featfeat/apigw custom domain
serverless-tencent/tencent-component-toolkit pull request #195
Opened 2021-02-20 07:01 UTC by wwwzbwcom

2021-02-20 07:31 UTC, wwwzbwcom commented
Apigw 自定义域名在每次部署时都会解绑再重新绑定，会导致用户服务中断。
并在解绑成功，绑定失败时会导致用户服务自定义域名失效。

现在改为有变更时才重新绑定

2021-02-22 03:25 UTC, yugasun requested changes

2021-02-22 03:25 UTC, yugasun commented on src/modules/apigw/index.ts
> +    if (deepEqual(currentDict, newDict)) {
这里自定义域名比对，可否一个一个域名比对，而不是所有域名比对，这样可以更细粒度的更新自定义域名

2021-02-22 03:47 UTC, wwwzbwcom commented on src/modules/apigw/index.ts
> +    if (deepEqual(currentDict, newDict)) {
可以，本来想先出一个版本，现在改一下

2021-02-22 07:04 UTC, yugasun requested changes

2021-02-22 07:04 UTC, yugasun commented on src/modules/apigw/index.ts
> +          if (currentDict[domain] && deepEqual(currentDict[domain], newDict[domain])) {
这里逻辑有问题？满足 `云端已经存在配置` 和 `云端配置和用户配置一样` 才进行绑定吗？

2021-02-22 08:16 UTC, wwwzbwcom commented on src/modules/apigw/index.ts
> +          if (currentDict[domain] && deepEqual(currentDict[domain], newDict[domain])) {
这部分逻辑反了，如果一个域名

- 云端配置存在并且和用户配置一样：会跳过解绑和绑定
- 否则，解绑后再重新绑定，以更新配置或删除过期的域名

2021-02-22 08:17 UTC, wwwzbwcom commented on src/modules/apigw/index.ts
> +          if (currentDict[domain] && deepEqual(currentDict[domain], newDict[domain])) {
已经修正，并添加测试验证域名实际绑定情况

2021-02-22 09:15 UTC, yugasun requested changes

2021-02-22 09:15 UTC, yugasun commented on src/modules/apigw/index.ts
> +      customDomains = [];
这里先保持之前逻辑，以免导致用户在控制台手动创建了，被 CLI 主动删除了。具体用户如果没配置特定参数，需不需要删除用户手动配置操作，这里需要从产品侧统一制定规则，然后处理。

2021-02-22 09:23 UTC, wwwzbwcom commented on src/modules/apigw/index.ts
> +      customDomains = [];
不会被 CLI 主动删除，之前代码中 unbind 的时候就会检查 oldState，只有在 oldState 中存在的自定义域名才会删除（可见 `unbindCustomDomain` 函数）

2021-02-22 09:25 UTC, yugasun requested changes

2021-02-22 09:25 UTC, yugasun commented on src/modules/apigw/index.ts
> +    console.log({ oldCustomDomains });
删除无用的 log

2021-02-22 09:25 UTC, yugasun requested changes

2021-02-22 09:25 UTC, yugasun commented on src/modules/apigw/index.ts
> +        console.log({ domain, currentDict, newDict });
删除无用 log

2021-02-22 09:28 UTC, wwwzbwcom commented on src/modules/apigw/index.ts
> +        console.log({ domain, currentDict, newDict });
已经删除

2021-02-22 09:28 UTC, wwwzbwcom commented on src/modules/apigw/index.ts
> +    console.log({ oldCustomDomains });
已经删除

2021-02-22 09:30 UTC, yugasun commented on src/modules/apigw/index.ts
> +      customDomains = [];
ok，这里逻辑没问题

2021-02-22 09:47 UTC, yugasun approved these changes

2021-02-22 10:31 UTC, merged

2021-02-22 10:32 UTC, slsplus commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/tencent-component-toolkit/v/2.2.0)
- [GitHub release](https://github.com/serverless-tencent/tencent-component-toolkit/releases/tag/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: